#include <iostream>
#include <string.h>
#include <TFile.h>
#include <TCanvas.h>
#include <TH1.h>
#include <TH2.h>
//#include <TPad.h>

// int histoCompare_ZHchannel( char * IVF_file ){
int histoCompare_ZHchannel( void ){

  gROOT->SetStyle("Plain");
  gStyle->SetOptTitle(0);
  gStyle->SetPalette(1);

  TCanvas * c0 = new TCanvas("c0","c0", 600, 600);
  TCanvas * c1 = new TCanvas("c1","c1", 600, 600);
  TCanvas * c2 = new TCanvas("c2","c2", 600, 600);
  TCanvas * c3 = new TCanvas("c3","c3", 600, 600);
  TCanvas * c4 = new TCanvas("c4","c4", 600, 600);
  TCanvas * c5 = new TCanvas("c5","c5", 600, 600);
  TCanvas * c6 = new TCanvas("c6","c6", 600, 600);
  TCanvas * c7 = new TCanvas("c7","c7", 600, 600);
  TCanvas * c8 = new TCanvas("c8","c8", 600, 600);
  TCanvas * c9 = new TCanvas("c9","c9", 600, 600);
//   TCanvas * c10 = new TCanvas("c10","c10", 600, 600);
//   TCanvas * c11 = new TCanvas("c11","c11", 600, 600);
//   TCanvas * c12 = new TCanvas("c12","c12", 600, 600);
//   TCanvas * c13 = new TCanvas("c13","c13", 600, 600);
//   TCanvas * c14 = new TCanvas("c14","c14", 600, 600);
//   TCanvas * c15 = new TCanvas("c15","c15", 600, 600);
//   TCanvas * c16 = new TCanvas("c16","c16", 600, 600);
//   TCanvas * c17 = new TCanvas("c17","c17", 600, 600);
//   TCanvas * c18 = new TCanvas("c18","c18", 600, 600);
//   TCanvas * c19 = new TCanvas("c19","c19", 600, 600);

//   TCanvas * c111 = new TCanvas("c111","c111", 600, 600);
//   TCanvas * c112 = new TCanvas("c112","c112", 600, 600);
//   TCanvas * c113 = new TCanvas("c113","c113", 600, 600);
//   TCanvas * c114 = new TCanvas("c114","c114", 600, 600);
//   TCanvas * c115 = new TCanvas("c115","c115", 600, 600);
//   TCanvas * c116 = new TCanvas("c116","c116", 600, 600);
//   TCanvas * c117 = new TCanvas("c117","c117", 600, 600);
//   TCanvas * c118 = new TCanvas("c118","c118", 600, 600);

//   TCanvas * c120 = new TCanvas("c120","c120", 600, 600);
//   TCanvas * c121 = new TCanvas("c121","c121", 600, 600);
//   TCanvas * c122 = new TCanvas("c122","c122", 600, 600);
//   TCanvas * c123 = new TCanvas("c123","c123", 600, 600);
//   TCanvas * c124 = new TCanvas("c124","c124", 600, 600);
//   TCanvas * c125 = new TCanvas("c125","c125", 600, 600);
//   TCanvas * c126 = new TCanvas("c126","c126", 600, 600);
//   TCanvas * c127 = new TCanvas("c127","c127", 600, 600);
//   TCanvas * c128 = new TCanvas("c128","c128", 600, 600);
//   TCanvas * c129 = new TCanvas("c129","c129", 600, 600);
//   TCanvas * c130 = new TCanvas("c130","c130", 600, 600);
//   TCanvas * c131 = new TCanvas("c131","c131", 600, 600);
//   TCanvas * c132 = new TCanvas("c132","c132", 600, 600);

// //Bidimensional histograms

  TCanvas * c20 = new TCanvas("c20","c20", 600, 600);
  TCanvas * c21 = new TCanvas("c21","c21", 600, 600);
  TCanvas * c22 = new TCanvas("c22","c22", 600, 600);
  TCanvas * c23 = new TCanvas("c23","c23", 600, 600);
  TCanvas * c24 = new TCanvas("c24","c24", 600, 600);
  TCanvas * c25 = new TCanvas("c25","c25", 600, 600);
  TCanvas * c26 = new TCanvas("c26","c26", 600, 600);
  TCanvas * c27 = new TCanvas("c27","c27", 600, 600);
  TCanvas * c28 = new TCanvas("c28","c28", 600, 600);
//   TCanvas * c29 = new TCanvas("c29","c29", 600, 600);


  TCanvas * c30 = new TCanvas("c30","c30", 600, 600);
  TCanvas * c31 = new TCanvas("c31","c31", 600, 600);
  TCanvas * c32 = new TCanvas("c32","c32", 600, 600);
  TCanvas * c33 = new TCanvas("c33","c33", 600, 600);
  TCanvas * c34 = new TCanvas("c34","c34", 600, 600);
  TCanvas * c35 = new TCanvas("c35","c35", 600, 600);
  TCanvas * c36 = new TCanvas("c36","c36", 600, 600);
  TCanvas * c37 = new TCanvas("c37","c37", 600, 600);
  TCanvas * c38 = new TCanvas("c38","c38", 600, 600);
  TCanvas * c39 = new TCanvas("c39","c39", 600, 600);

  TCanvas * c40 = new TCanvas("c40","c40", 600, 600);
  TCanvas * c41 = new TCanvas("c41","c41", 600, 600);
  TCanvas * c42 = new TCanvas("c42","c42", 600, 600);
  TCanvas * c43 = new TCanvas("c43","c43", 600, 600);
  TCanvas * c44 = new TCanvas("c44","c44", 600, 600);
  TCanvas * c45 = new TCanvas("c45","c45", 600, 600);
  TCanvas * c46 = new TCanvas("c46","c46", 600, 600);
  TCanvas * c47 = new TCanvas("c47","c47", 600, 600);
  TCanvas * c48 = new TCanvas("c48","c48", 600, 600);
  TCanvas * c49 = new TCanvas("c49","c49", 600, 600);

  TCanvas * c50 = new TCanvas("c50","c50", 600, 600);
  TCanvas * c51 = new TCanvas("c51","c51", 600, 600);
  TCanvas * c52 = new TCanvas("c52","c52", 600, 600);
  TCanvas * c53 = new TCanvas("c53","c53", 600, 600);
  TCanvas * c54 = new TCanvas("c54","c54", 600, 600);
  TCanvas * c55 = new TCanvas("c55","c55", 600, 600);
  TCanvas * c56 = new TCanvas("c56","c56", 600, 600);
  TCanvas * c57 = new TCanvas("c57","c57", 600, 600);
  TCanvas * c58 = new TCanvas("c58","c58", 600, 600);
  TCanvas * c59 = new TCanvas("c59","c59", 600, 600);

//  TFile::Open("./ZH_channel_cut/ZH_channel_signal//ZH_channel_signal.root");
//    TFile::Open("./ZH_channel_cut/ZH_channel_signal/ZH_channel_signal.root");

  std::string path = "./ZH_channel_v3";
  std::string subDir = "ZHchannel";
  std::string additional = "_v3";

  std::string signal = path+"/ZH_channel_signal"+additional.c_str()+"/ZH_channel_signal"+additional.c_str()+".root";
  TFile::Open(signal.c_str());

  //Tagger : combinedSecondaryVertexBJetTags

  gDirectory->cd(subDir.c_str());

  c0->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_Zcandidate_mass->SetTitle("Z candidate mass");
  h_Zcandidate_mass->GetYaxis()->SetLabelSize(0.03);
  h_Zcandidate_mass->GetXaxis()->SetLabelSize(0.03);
  h_Zcandidate_mass->GetXaxis()->SetRangeUser(70,110);
  h_Zcandidate_mass->SetMarkerStyle(21);
  h_Zcandidate_mass->SetFillColor(kCyan);
  h_Zcandidate_mass->SetFillStyle(3002);
  h_Zcandidate_mass->SetMarkerColor(kBlack);
  h_Zcandidate_mass->DrawNormalized();

  c1->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_higgsCandidate_mass->SetTitle("higgs candidate mass");
  h_higgsCandidate_mass->GetYaxis()->SetLabelSize(0.03);
  h_higgsCandidate_mass->GetXaxis()->SetLabelSize(0.03);
  h_higgsCandidate_mass->Rebin(8);
  h_higgsCandidate_mass->SetMarkerStyle(21);
  h_higgsCandidate_mass->SetFillColor(kCyan);
  h_higgsCandidate_mass->SetFillStyle(3002);
  h_higgsCandidate_mass->SetMarkerColor(kBlack);
  h_higgsCandidate_mass->DrawNormalized();

  c2->cd();
  //  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_deltaTheta->SetTitle("Pull angle");
  h_deltaTheta->Rebin(10);
  h_deltaTheta->GetYaxis()->SetTitle("#Delta #theta_{t}");
  h_deltaTheta->GetYaxis()->SetLabelSize(0.03);
  h_deltaTheta->GetXaxis()->SetLabelSize(0.03);
  h_deltaTheta->GetXaxis()->SetRangeUser(-4,4);
  h_deltaTheta->SetMarkerStyle(21);
  h_deltaTheta->SetFillColor(kCyan);
  h_deltaTheta->SetFillStyle(3002);
  h_deltaTheta->SetMarkerColor(kBlack);
  h_deltaTheta->DrawNormalized();

  c3->cd();
  //  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_HigherDeltaTheta->SetTitle("Pull angle leading jet");
  h_HigherDeltaTheta->Rebin(10);
  h_HigherDeltaTheta->GetYaxis()->SetTitle("#Delta #theta_{t}");
  h_HigherDeltaTheta->GetYaxis()->SetLabelSize(0.03);
  h_HigherDeltaTheta->GetXaxis()->SetLabelSize(0.03);
  h_HigherDeltaTheta->GetXaxis()->SetRangeUser(-4,4);
  h_HigherDeltaTheta->SetMarkerStyle(21);
  h_HigherDeltaTheta->SetFillColor(kCyan);
  h_HigherDeltaTheta->SetFillStyle(3002);
  h_HigherDeltaTheta->SetMarkerColor(kBlack);
  h_HigherDeltaTheta->DrawNormalized();
 
  c4->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_LowerDeltaTheta->SetTitle("Pull angle second leading let");
  h_LowerDeltaTheta->Rebin(10);
  h_LowerDeltaTheta->GetXaxis()->SetTitle("#Delta #theta_{t}");
  h_LowerDeltaTheta->GetYaxis()->SetLabelSize(0.03);
  h_LowerDeltaTheta->GetXaxis()->SetLabelSize(0.03);
  h_LowerDeltaTheta->GetXaxis()->SetRangeUser(-4,4);
  h_LowerDeltaTheta->SetMarkerStyle(21);
  h_LowerDeltaTheta->SetFillColor(kCyan);
  h_LowerDeltaTheta->SetFillStyle(3002);
  h_LowerDeltaTheta->SetMarkerColor(kBlack);
  h_LowerDeltaTheta->DrawNormalized();

  c5->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_jetDeltaEtaGeneral->SetTitle("Jet #Delta #eta");
  h_jetDeltaEtaGeneral->Rebin(4);
  h_jetDeltaEtaGeneral->GetYaxis()->SetLabelSize(0.03);
  h_jetDeltaEtaGeneral->GetXaxis()->SetLabelSize(0.03);
  h_jetDeltaEtaGeneral->GetXaxis()->SetRangeUser(-0.1,3);
  h_jetDeltaEtaGeneral->SetMarkerStyle(21);
  h_jetDeltaEtaGeneral->SetFillColor(kCyan);
  h_jetDeltaEtaGeneral->SetFillStyle(3002);
  h_jetDeltaEtaGeneral->SetMarkerColor(kBlack);
  h_jetDeltaEtaGeneral->DrawNormalized();

  c6->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_jetDeltaR_general->SetTitle("Jet #Delta R");
  h_jetDeltaR_general->Rebin(4);
  h_jetDeltaR_general->GetYaxis()->SetLabelSize(0.03);
  h_jetDeltaR_general->GetXaxis()->SetLabelSize(0.03);
  h_jetDeltaR_general->GetXaxis()->SetRangeUser(0,5);
  h_jetDeltaR_general->SetMarkerStyle(21);
  h_jetDeltaR_general->SetFillColor(kCyan);
  h_jetDeltaR_general->SetFillStyle(3002);
  h_jetDeltaR_general->SetMarkerColor(kBlack);
  h_jetDeltaR_general->DrawNormalized();

  c7->cd();
  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_invmassJet_general->SetTitle("Jet mass");
  h_invmassJet_general->Rebin(8);
  h_invmassJet_general->GetYaxis()->SetTitle("mass");
  h_invmassJet_general->GetYaxis()->SetLabelSize(0.03);
  h_invmassJet_general->GetXaxis()->SetLabelSize(0.03);
  h_invmassJet_general->SetMarkerStyle(21);
  h_invmassJet_general->SetFillColor(kCyan);
  h_invmassJet_general->SetFillStyle(3002);
  h_invmassJet_general->SetMarkerColor(kBlack);
  h_invmassJet_general->DrawNormalized();

  c8->cd();
  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_jetPtAsymmetryGeneral->SetTitle("Pt Asymmetry");
  h_jetPtAsymmetryGeneral->Rebin(4);
  h_jetPtAsymmetryGeneral->GetYaxis()->SetLabelSize(0.03);
  h_jetPtAsymmetryGeneral->GetXaxis()->SetLabelSize(0.03);
  h_jetPtAsymmetryGeneral->SetMarkerStyle(21);
  h_jetPtAsymmetryGeneral->SetFillColor(kCyan);
  h_jetPtAsymmetryGeneral->SetFillStyle(3002);
  h_jetPtAsymmetryGeneral->SetMarkerColor(kBlack);
  h_jetPtAsymmetryGeneral->DrawNormalized();

  c9->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_digammaAbsDeltatheta_invmassJet->ProjectionX("h_deltaTheta_signal_central",300, 420);
  TH1D * h_integral_signal = new TH1D("h_integral_signal","h_integral_signal", 30, 0, 30);
  h_deltaTheta_signal_central->Rebin(10);
  h_deltaTheta_signal_central->Sumw2();
  double integral_tmp = h_deltaTheta_signal_central->Integral();
  h_deltaTheta_signal_central->Scale( (double)1/integral_tmp );
  for(int i = 0; i < 30; i++) {
    std::cout <<  h_deltaTheta_signal_central->Integral(0+15,i+15) << std::endl;
    h_integral_signal->SetBinContent( i, h_deltaTheta_signal_central->Integral(0+15,i+15) );
  }
  h_integral_signal->GetXaxis()->SetTitle("h_integral");
  h_integral_signal->GetXaxis()->SetLabelSize(0.03);
  h_integral_signal->SetMarkerStyle(21);
  h_integral_signal->SetFillColor(kCyan);
  h_integral_signal->SetFillStyle(3002);
  h_integral_signal->SetMarkerColor(kBlack);
  h_integral_signal->Draw();


  c20->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_jetDeltaR_higgsCandidateMass->SetTitle("deltaR vs higgsMass signal");
  h2_jetDeltaR_higgsCandidateMass->GetYaxis()->SetTitle("higgsMass");
  h2_jetDeltaR_higgsCandidateMass->GetXaxis()->SetTitle("deltaR");
  h2_jetDeltaR_higgsCandidateMass->RebinX(2);
  h2_jetDeltaR_higgsCandidateMass->RebinY(16);
  h2_jetDeltaR_higgsCandidateMass->GetYaxis()->SetLabelSize(0.03);
  h2_jetDeltaR_higgsCandidateMass->GetYaxis()->SetRangeUser(60,160);
  h2_jetDeltaR_higgsCandidateMass->GetXaxis()->SetLabelSize(0.03);
  h2_jetDeltaR_higgsCandidateMass->GetXaxis()->SetRangeUser(0,4);
  h2_jetDeltaR_higgsCandidateMass->SetMarkerStyle(21);
  h2_jetDeltaR_higgsCandidateMass->SetFillColor(kCyan);
  h2_jetDeltaR_higgsCandidateMass->SetFillStyle(3002);
  h2_jetDeltaR_higgsCandidateMass->SetMarkerColor(kBlack);
  h2_jetDeltaR_higgsCandidateMass->DrawNormalized("COLZ");
  c20->Print("ZH_channel_v3/plots/c20.png");

  c23->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_jetDeltaR_jetPtAsymmetry->SetTitle("deltaR vs ptasymmetry signal");
  h2_jetDeltaR_jetPtAsymmetry->GetYaxis()->SetTitle("ptAsymmetry");
  h2_jetDeltaR_jetPtAsymmetry->GetXaxis()->SetTitle("deltaR");
  h2_jetDeltaR_jetPtAsymmetry->GetYaxis()->SetLabelSize(0.03);
  h2_jetDeltaR_jetPtAsymmetry->GetYaxis()->SetRangeUser(60,160);
  h2_jetDeltaR_jetPtAsymmetry->GetXaxis()->SetLabelSize(0.03);
  h2_jetDeltaR_jetPtAsymmetry->GetXaxis()->SetRangeUser(0,4);
  h2_jetDeltaR_jetPtAsymmetry->SetMarkerStyle(21);
  h2_jetDeltaR_jetPtAsymmetry->SetFillColor(kCyan);
  h2_jetDeltaR_jetPtAsymmetry->SetFillStyle(3002);
  h2_jetDeltaR_jetPtAsymmetry->SetMarkerColor(kBlack);
  h2_jetDeltaR_jetPtAsymmetry->DrawNormalized("COLZ");
  c23->Print("ZH_channel_v3/plots/c23.png");

  c26->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_jetDeltaEta_jetDeltaR->SetTitle("deltaR vs ptasymmetry signal");
  h2_jetDeltaEta_jetDeltaR->GetYaxis()->SetTitle("#Delta R");
  h2_jetDeltaEta_jetDeltaR->GetXaxis()->SetTitle("#Delta #eta");
  h2_jetDeltaEta_jetDeltaR->GetYaxis()->SetLabelSize(0.03);
  h2_jetDeltaEta_jetDeltaR->GetYaxis()->SetRangeUser(60,160);
  h2_jetDeltaEta_jetDeltaR->GetXaxis()->SetLabelSize(0.03);
  h2_jetDeltaEta_jetDeltaR->GetXaxis()->SetRangeUser(0,4);
  h2_jetDeltaEta_jetDeltaR->SetMarkerStyle(21);
  h2_jetDeltaEta_jetDeltaR->SetFillColor(kCyan);
  h2_jetDeltaEta_jetDeltaR->SetFillStyle(3002);
  h2_jetDeltaEta_jetDeltaR->SetMarkerColor(kBlack);
  h2_jetDeltaEta_jetDeltaR->DrawNormalized("COLZ");
  c26->Print("ZH_channel_v3/plots/c26.png");

  c30->cd();
  //  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_deltaTheta_invmassJet->SetTitle("Pull angle vs invmass");
  h2_deltaTheta_invmassJet->GetXaxis()->SetTitle("#Delta #theta_{t}");
  h2_deltaTheta_invmassJet->GetYaxis()->SetTitle("M_{jj}");
  h2_deltaTheta_invmassJet->RebinY(10);
  h2_deltaTheta_invmassJet->RebinX(10);
  h2_deltaTheta_invmassJet->GetYaxis()->SetLabelSize(0.03);
  h2_deltaTheta_invmassJet->GetXaxis()->SetLabelSize(0.03);
  h2_deltaTheta_invmassJet->GetXaxis()->SetRangeUser(-4,4);
  h2_deltaTheta_invmassJet->SetMarkerStyle(21);
  h2_deltaTheta_invmassJet->SetFillColor(kCyan);
  h2_deltaTheta_invmassJet->SetFillStyle(3002);
  h2_deltaTheta_invmassJet->SetMarkerColor(kBlack);
  h2_deltaTheta_invmassJet->DrawNormalized("COLZ");
  c30->Print("ZH_channel_v3/plots/c30.png");

  c33->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_deltaTheta_JetDeltaR->SetTitle("Pull angle vs jet dR");
  h2_deltaTheta_JetDeltaR->RebinX(10);
  h2_deltaTheta_JetDeltaR->RebinY(10);
  h2_deltaTheta_JetDeltaR->GetYaxis()->SetTitle("M_{jj}");
  h2_deltaTheta_JetDeltaR->GetXaxis()->SetTitle("#Delta #theta_{t}");
  h2_deltaTheta_JetDeltaR->GetYaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaR->GetXaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaR->GetXaxis()->SetRangeUser(-4,4);
  h2_deltaTheta_JetDeltaR->SetMarkerStyle(21);
  h2_deltaTheta_JetDeltaR->SetFillColor(kCyan);
  h2_deltaTheta_JetDeltaR->SetFillStyle(3002);
  h2_deltaTheta_JetDeltaR->SetMarkerColor(kBlack);
  h2_deltaTheta_JetDeltaR->DrawNormalized("COLZ");
  c33->Print("ZH_channel_v3/plots/c33.png");
 
  c36->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_deltaTheta_JetDeltaEta->SetTitle("Pull angle vs dEta");
  h2_deltaTheta_JetDeltaEta->RebinX(10);
  h2_deltaTheta_JetDeltaEta->RebinY(10);
  h2_deltaTheta_JetDeltaEta->GetXaxis()->SetTitle("#Delta #theta_{t}");
  h2_deltaTheta_JetDeltaEta->GetYaxis()->SetTitle("M_{jj}");
  h2_deltaTheta_JetDeltaEta->GetYaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaEta->GetXaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaEta->GetXaxis()->SetRangeUser(-4,4);
  h2_deltaTheta_JetDeltaEta->SetMarkerStyle(21);
  h2_deltaTheta_JetDeltaEta->SetFillColor(kCyan);
  h2_deltaTheta_JetDeltaEta->SetFillStyle(3002);
  h2_deltaTheta_JetDeltaEta->SetMarkerColor(kBlack);
  h2_deltaTheta_JetDeltaEta->DrawNormalized("COLZ");
  c36->Print("ZH_channel_v3/plots/c36.png");

  c39->cd();
  //  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_deltaTheta_JetDeltaPhi->SetTitle("Pull angle vs dPhi"); 
  h2_deltaTheta_JetDeltaPhi->RebinY(10);
  h2_deltaTheta_JetDeltaPhi->RebinX(10);
  h2_deltaTheta_JetDeltaPhi->GetXaxis()->SetTitle("#Delta #theta_{t}"); 
  h2_deltaTheta_JetDeltaPhi->GetYaxis()->SetTitle("M_{jj}"); 
  h2_deltaTheta_JetDeltaPhi->GetYaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaPhi->GetXaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaPhi->GetXaxis()->SetRangeUser(-4,4);
  h2_deltaTheta_JetDeltaPhi->SetMarkerStyle(21);
  h2_deltaTheta_JetDeltaPhi->SetFillColor(kCyan);
  h2_deltaTheta_JetDeltaPhi->SetFillStyle(3002);
  h2_deltaTheta_JetDeltaPhi->SetMarkerColor(kBlack);
  h2_deltaTheta_JetDeltaPhi->DrawNormalized("COLZ");
  c39->Print("ZH_channel_v3/plots/c39.png");


  c48->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_JetDeltaEta_invmassJet->SetTitle("Jet #Delta #eta general");
  h2_JetDeltaEta_invmassJet->RebinX(4);
  h2_JetDeltaEta_invmassJet->RebinY(10);
  h2_JetDeltaEta_invmassJet->GetYaxis()->SetLabelSize(0.03);
  h2_JetDeltaEta_invmassJet->GetXaxis()->SetLabelSize(0.03);
  h2_JetDeltaEta_invmassJet->GetXaxis()->SetRangeUser(-0.1,3);
  h2_JetDeltaEta_invmassJet->SetMarkerStyle(21);
  h2_JetDeltaEta_invmassJet->SetFillColor(kCyan);
  h2_JetDeltaEta_invmassJet->SetFillStyle(3002);
  h2_JetDeltaEta_invmassJet->SetMarkerColor(kBlack);
  h2_JetDeltaEta_invmassJet->DrawNormalized("COLZ");
  c48->Print("ZH_channel_v3/plots/c48.png");

  c51->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_JetDeltaR_invmassJet->SetTitle("Jet #Delta R general");
  h2_JetDeltaR_invmassJet->RebinX(4);
  h2_JetDeltaR_invmassJet->RebinY(10);
  h2_JetDeltaR_invmassJet->GetYaxis()->SetLabelSize(0.03);
  h2_JetDeltaR_invmassJet->GetXaxis()->SetLabelSize(0.03);
  h2_JetDeltaR_invmassJet->GetXaxis()->SetRangeUser(0,5);
  h2_JetDeltaR_invmassJet->SetMarkerStyle(21);
  h2_JetDeltaR_invmassJet->SetFillColor(kCyan);
  h2_JetDeltaR_invmassJet->SetFillStyle(3002);
  h2_JetDeltaR_invmassJet->SetMarkerColor(kBlack);
  h2_JetDeltaR_invmassJet->DrawNormalized("COLZ");
  c51->Print("ZH_channel_v3/plots/c51.png");

  c57->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_jetPtAsymmetry_invmassJet->RebinX(8);
  h2_jetPtAsymmetry_invmassJet->RebinY(10);
  h2_jetPtAsymmetry_invmassJet->SetTitle("pt_asymmetry_invmass");
  h2_jetPtAsymmetry_invmassJet->GetYaxis()->SetTitle("inv_mass");
  h2_jetPtAsymmetry_invmassJet->GetXaxis()->SetTitle("jet pt asymmetry");
  h2_jetPtAsymmetry_invmassJet->GetYaxis()->SetLabelSize(0.03);
  h2_jetPtAsymmetry_invmassJet->GetXaxis()->SetLabelSize(0.03);
  h2_jetPtAsymmetry_invmassJet->SetMarkerStyle(21);
  h2_jetPtAsymmetry_invmassJet->SetFillColor(kCyan);
  h2_jetPtAsymmetry_invmassJet->SetFillStyle(3002);
  h2_jetPtAsymmetry_invmassJet->SetMarkerColor(kBlack);
  h2_jetPtAsymmetry_invmassJet->DrawNormalized("COLZ");
  c57->Print("ZH_channel_v3/plots/c57.png");



// QUI METTIAMO il background fatto da QCD (dati)
  std::string background_QCD = path+"/ZH_channel_QCD"+additional.c_str()+"/ZH_channel_QCD"+additional.c_str()+".root";
  TFile::Open(background_QCD.c_str());

  //Tagger : combinedSecondaryVertexBJetTags

  gDirectory->cd("MultiJet");

//   c0->cd();
// //   gPad->SetLogy();
//   gPad->SetGridy();
//   gPad->SetGridx();
//   h_Zcandidate_mass->SetTitle("Z candidate mass VJets QCD");
//   h_Zcandidate_mass->GetYaxis()->SetLabelSize(0.03);
//   h_Zcandidate_mass->GetXaxis()->SetLabelSize(0.03);
//   h_Zcandidate_mass->GetXaxis()->SetRangeUser(70,110);
//   h_Zcandidate_mass->SetMarkerStyle(21);
//   h_Zcandidate_mass->SetFillColor(kGreen);
//   h_Zcandidate_mass->SetFillStyle(3002);
//   h_Zcandidate_mass->SetMarkerColor(kBlack);
//   h_Zcandidate_mass->DrawNormalized("same");

//   c1->cd();
// //   gPad->SetLogy();
//   gPad->SetGridy();
//   gPad->SetGridx();
//   h_gluonCandidate_mass->SetTitle("gluon candidate mass VJets QCD");
//   h_gluonCandidate_mass->GetYaxis()->SetLabelSize(0.03);
//   h_gluonCandidate_mass->GetXaxis()->SetLabelSize(0.03);
//   h_gluonCandidate_mass->Rebin(8);
//   h_gluonCandidate_mass->SetMarkerStyle(21);
//   h_gluonCandidate_mass->SetFillColor(kGreen);
//   h_gluonCandidate_mass->SetFillStyle(3002);
//   h_gluonCandidate_mass->SetMarkerColor(kBlack);
//   h_gluonCandidate_mass->DrawNormalized("same");

  c2->cd();
  //  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_deltaTheta->SetTitle("Pull angle VJets QCD");
  h_deltaTheta->Rebin(10);
  h_deltaTheta->GetYaxis()->SetTitle("#Delta #theta_{t}");
  h_deltaTheta->GetYaxis()->SetLabelSize(0.03);
  h_deltaTheta->GetXaxis()->SetLabelSize(0.03);
  h_deltaTheta->GetXaxis()->SetRangeUser(-4,4);
  h_deltaTheta->SetMarkerStyle(21);
  h_deltaTheta->SetFillColor(kGreen);
  h_deltaTheta->SetFillStyle(3002);
  h_deltaTheta->SetMarkerColor(kBlack);
  h_deltaTheta->DrawNormalized("same");

  c3->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_HigherDeltaTheta->SetTitle("Pull angle leading jet VJets QCD");
  h_HigherDeltaTheta->Rebin(10);
  h_HigherDeltaTheta->GetYaxis()->SetTitle("#Delta #theta_{t}");
  h_HigherDeltaTheta->GetYaxis()->SetLabelSize(0.03);
  h_HigherDeltaTheta->GetXaxis()->SetLabelSize(0.03);
  h_HigherDeltaTheta->GetXaxis()->SetRangeUser(-4,4);
  h_HigherDeltaTheta->SetMarkerStyle(21);
  h_HigherDeltaTheta->SetFillColor(kGreen);
  h_HigherDeltaTheta->SetFillStyle(3002);
  h_HigherDeltaTheta->SetMarkerColor(kBlack);
  h_HigherDeltaTheta->DrawNormalized("same");

  c4->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_LowerDeltaTheta->SetTitle("Pull angle second leading jet VJets QCD");
  h_LowerDeltaTheta->Rebin(10);
  h_LowerDeltaTheta->GetYaxis()->SetLabelSize(0.03);
  h_LowerDeltaTheta->GetXaxis()->SetLabelSize(0.03);
  h_LowerDeltaTheta->GetXaxis()->SetRangeUser(-4,4);
  h_LowerDeltaTheta->SetMarkerStyle(21);
  h_LowerDeltaTheta->SetFillColor(kGreen);
  h_LowerDeltaTheta->SetFillStyle(3002);
  h_LowerDeltaTheta->SetMarkerColor(kBlack);
  h_LowerDeltaTheta->DrawNormalized("same");

//   c5->cd();
// //   gPad->SetLogy();
//   gPad->SetGridy();
//   gPad->SetGridx();
//   h_jetDeltaEtaGeneral->SetTitle("Jet #Delta #eta general VJets QCD");
//   h_jetDeltaEtaGeneral->Rebin(4);
//   h_jetDeltaEtaGeneral->GetYaxis()->SetLabelSize(0.03);
//   h_jetDeltaEtaGeneral->GetXaxis()->SetLabelSize(0.03);
//   h_jetDeltaEtaGeneral->GetXaxis()->SetRangeUser(-0.1,3);
//   h_jetDeltaEtaGeneral->SetMarkerStyle(21);
//   h_jetDeltaEtaGeneral->SetFillColor(kGreen);
//   h_jetDeltaEtaGeneral->SetFillStyle(3002);
//   h_jetDeltaEtaGeneral->SetMarkerColor(kBlack);
//   h_jetDeltaEtaGeneral->DrawNormalized("same");

//   c6->cd();
// //   gPad->SetLogy();
//   gPad->SetGridy();
//   gPad->SetGridx();
//   h_jetDeltaR_general->SetTitle("Jet #Delta R general VJets QCD");
//   h_jetDeltaR_general->Rebin(4);
//   h_jetDeltaR_general->GetYaxis()->SetLabelSize(0.03);
//   h_jetDeltaR_general->GetXaxis()->SetLabelSize(0.03);
//   h_jetDeltaR_general->GetXaxis()->SetRangeUser(0,5);
//   h_jetDeltaR_general->SetMarkerStyle(21);
//   h_jetDeltaR_general->SetFillColor(kGreen);
//   h_jetDeltaR_general->SetFillStyle(3002);
//   h_jetDeltaR_general->SetMarkerColor(kBlack);
//   h_jetDeltaR_general->DrawNormalized("same");

//   c7->cd();
//   gPad->SetLogy();
//   gPad->SetGridy();
//   gPad->SetGridx();
//   h_invmassJet_general->SetTitle("Jet mass VJets QCD");
//   h_invmassJet_general->Rebin(8);
//   h_invmassJet_general->GetYaxis()->SetTitle("mass");
//   h_invmassJet_general->GetYaxis()->SetLabelSize(0.03);
//   h_invmassJet_general->GetXaxis()->SetLabelSize(0.03);
//   h_invmassJet_general->SetMarkerStyle(21);
//   h_invmassJet_general->SetFillColor(kGreen);
//   h_invmassJet_general->SetFillStyle(3002);
//   h_invmassJet_general->SetMarkerColor(kBlack);
//   h_invmassJet_general->DrawNormalized("same");

//   c8->cd();
//   gPad->SetLogy();
//   gPad->SetGridy();
//   gPad->SetGridx();
//   h_jetPtAsymmetryGeneral->SetTitle("Pt Asymmetry VJets QCD");
//   h_jetPtAsymmetryGeneral->Rebin(4);
//   h_jetPtAsymmetryGeneral->GetYaxis()->SetLabelSize(0.03);
//   h_jetPtAsymmetryGeneral->GetXaxis()->SetLabelSize(0.03);
//   h_jetPtAsymmetryGeneral->SetMarkerStyle(21);
//   h_jetPtAsymmetryGeneral->SetFillColor(kGreen);
//   h_jetPtAsymmetryGeneral->SetFillStyle(3002);
//   h_jetPtAsymmetryGeneral->SetMarkerColor(kBlack);
//   h_jetPtAsymmetryGeneral->DrawNormalized("same");

  c9->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_absDeltatheta_invmassJet->ProjectionX("h_deltaTheta_QCD_central",300, 420);
  TH1D * h_integral_QCD = new TH1D("h_integral_QCD","h_integral_QCD", 30, 0, 30);
  h_deltaTheta_QCD_central->Rebin(10);
  h_deltaTheta_QCD_central->Sumw2();
  double integral_tmp = h_deltaTheta_QCD_central->Integral();
  h_deltaTheta_QCD_central->Scale( (double)1/integral_tmp );
  for(int i = 0; i < 30; i++) {
    std::cout <<  h_deltaTheta_QCD_central->Integral(0+15,i+15) << std::endl;
    h_integral_QCD->SetBinContent( i, h_deltaTheta_QCD_central->Integral(0+15,i+15) );
  }
  h_integral_QCD->GetXaxis()->SetTitle("h_integral");
  h_integral_QCD->GetXaxis()->SetLabelSize(0.03);
  h_integral_QCD->SetMarkerStyle(21);
  h_integral_QCD->SetFillColor(kCyan);
  h_integral_QCD->SetFillStyle(3002);
  h_integral_QCD->SetMarkerColor(kBlack);
  h_integral_QCD->Draw("same");

// QUI METTIAMO il background fatto da HERWIG (tanto si taglia in pt>150)
  std::string background_herwig = path+"/ZH_channel_background_herwig"+additional.c_str()+"/ZH_channel_background_herwig"+additional.c_str()+".root";
  TFile::Open(background_herwig.c_str());

  gDirectory->cd(subDir.c_str());

  c0->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_Zcandidate_mass->SetTitle("Z candidate mass VJets herwig");
  h_Zcandidate_mass->GetYaxis()->SetLabelSize(0.03);
  h_Zcandidate_mass->GetXaxis()->SetLabelSize(0.03);
  h_Zcandidate_mass->GetXaxis()->SetRangeUser(70,110);
  h_Zcandidate_mass->SetMarkerStyle(21);
  h_Zcandidate_mass->SetFillColor(kRed);
  h_Zcandidate_mass->SetFillStyle(3002);
  h_Zcandidate_mass->SetMarkerColor(kBlack);
  h_Zcandidate_mass->DrawNormalized("same");

  c1->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_higgsCandidate_mass->SetTitle("higgs candidate mass VJets herwig");
  h_higgsCandidate_mass->GetYaxis()->SetLabelSize(0.03);
  h_higgsCandidate_mass->GetXaxis()->SetLabelSize(0.03);
  h_higgsCandidate_mass->Rebin(8);
  h_higgsCandidate_mass->SetMarkerStyle(21);
  h_higgsCandidate_mass->SetFillColor(kRed);
  h_higgsCandidate_mass->SetFillStyle(3002);
  h_higgsCandidate_mass->SetMarkerColor(kBlack);
  h_higgsCandidate_mass->DrawNormalized("same");

  c2->cd();
  //  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_deltaTheta->SetTitle("Pull angle VJets herwig");
  h_deltaTheta->Rebin(10);
  h_deltaTheta->GetYaxis()->SetTitle("#Delta #theta_{t}");
  h_deltaTheta->GetYaxis()->SetLabelSize(0.03);
  h_deltaTheta->GetXaxis()->SetLabelSize(0.03);
  h_deltaTheta->GetXaxis()->SetRangeUser(-4,4);
  h_deltaTheta->SetMarkerStyle(21);
  h_deltaTheta->SetFillColor(kRed);
  h_deltaTheta->SetFillStyle(3002);
  h_deltaTheta->SetMarkerColor(kBlack);
  h_deltaTheta->DrawNormalized("same");

  c3->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_HigherDeltaTheta->SetTitle("Pull angle leading jet VJets herwig");
  h_HigherDeltaTheta->Rebin(10);
  h_HigherDeltaTheta->GetYaxis()->SetTitle("#Delta #theta_{t}");
  h_HigherDeltaTheta->GetYaxis()->SetLabelSize(0.03);
  h_HigherDeltaTheta->GetXaxis()->SetLabelSize(0.03);
  h_HigherDeltaTheta->GetXaxis()->SetRangeUser(-4,4);
  h_HigherDeltaTheta->SetMarkerStyle(21);
  h_HigherDeltaTheta->SetFillColor(kRed);
  h_HigherDeltaTheta->SetFillStyle(3002);
  h_HigherDeltaTheta->SetMarkerColor(kBlack);
  h_HigherDeltaTheta->DrawNormalized("same");

  c4->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_LowerDeltaTheta->SetTitle("Pull angle second leading jet VJets herwig");
  h_LowerDeltaTheta->Rebin(10);
  h_LowerDeltaTheta->GetYaxis()->SetLabelSize(0.03);
  h_LowerDeltaTheta->GetXaxis()->SetLabelSize(0.03);
  h_LowerDeltaTheta->GetXaxis()->SetRangeUser(-4,4);
  h_LowerDeltaTheta->SetMarkerStyle(21);
  h_LowerDeltaTheta->SetFillColor(kRed);
  h_LowerDeltaTheta->SetFillStyle(3002);
  h_LowerDeltaTheta->SetMarkerColor(kBlack);
  h_LowerDeltaTheta->DrawNormalized("same");

  c5->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_jetDeltaEtaGeneral->SetTitle("Jet #Delta #eta general VJets herwig");
  h_jetDeltaEtaGeneral->Rebin(4);
  h_jetDeltaEtaGeneral->GetYaxis()->SetLabelSize(0.03);
  h_jetDeltaEtaGeneral->GetXaxis()->SetLabelSize(0.03);
  h_jetDeltaEtaGeneral->GetXaxis()->SetRangeUser(-0.1,3);
  h_jetDeltaEtaGeneral->SetMarkerStyle(21);
  h_jetDeltaEtaGeneral->SetFillColor(kRed);
  h_jetDeltaEtaGeneral->SetFillStyle(3002);
  h_jetDeltaEtaGeneral->SetMarkerColor(kBlack);
  h_jetDeltaEtaGeneral->DrawNormalized("same");

  c6->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_jetDeltaR_general->SetTitle("Jet #Delta R general VJets herwig");
  h_jetDeltaR_general->Rebin(4);
  h_jetDeltaR_general->GetYaxis()->SetLabelSize(0.03);
  h_jetDeltaR_general->GetXaxis()->SetLabelSize(0.03);
  h_jetDeltaR_general->GetXaxis()->SetRangeUser(0,5);
  h_jetDeltaR_general->SetMarkerStyle(21);
  h_jetDeltaR_general->SetFillColor(kRed);
  h_jetDeltaR_general->SetFillStyle(3002);
  h_jetDeltaR_general->SetMarkerColor(kBlack);
  h_jetDeltaR_general->DrawNormalized("same");

  c7->cd();
  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_invmassJet_general->SetTitle("Jet mass VJets herwig");
  h_invmassJet_general->Rebin(8);
  h_invmassJet_general->GetYaxis()->SetTitle("mass");
  h_invmassJet_general->GetYaxis()->SetLabelSize(0.03);
  h_invmassJet_general->GetXaxis()->SetLabelSize(0.03);
  h_invmassJet_general->SetMarkerStyle(21);
  h_invmassJet_general->SetFillColor(kRed);
  h_invmassJet_general->SetFillStyle(3002);
  h_invmassJet_general->SetMarkerColor(kBlack);
  h_invmassJet_general->DrawNormalized("same");

  c8->cd();
  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_jetPtAsymmetryGeneral->SetTitle("Pt Asymmetry VJets herwig");
  h_jetPtAsymmetryGeneral->Rebin(4);
  h_jetPtAsymmetryGeneral->GetYaxis()->SetLabelSize(0.03);
  h_jetPtAsymmetryGeneral->GetXaxis()->SetLabelSize(0.03);
  h_jetPtAsymmetryGeneral->SetMarkerStyle(21);
  h_jetPtAsymmetryGeneral->SetFillColor(kRed);
  h_jetPtAsymmetryGeneral->SetFillStyle(3002);
  h_jetPtAsymmetryGeneral->SetMarkerColor(kBlack);
  h_jetPtAsymmetryGeneral->DrawNormalized("same");


  c21->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_jetDeltaR_higgsCandidateMass->SetTitle("deltaR vs higgsMass VJets herwig");
  h2_jetDeltaR_higgsCandidateMass->GetYaxis()->SetTitle("higgsMass");
  h2_jetDeltaR_higgsCandidateMass->GetYaxis()->SetTitle("deltaR");
  h2_jetDeltaR_higgsCandidateMass->RebinX(2);
  h2_jetDeltaR_higgsCandidateMass->RebinY(16);
  h2_jetDeltaR_higgsCandidateMass->GetYaxis()->SetLabelSize(0.03);
  h2_jetDeltaR_higgsCandidateMass->GetYaxis()->SetRangeUser(60,160);
  h2_jetDeltaR_higgsCandidateMass->GetXaxis()->SetLabelSize(0.03);
  h2_jetDeltaR_higgsCandidateMass->GetXaxis()->SetRangeUser(0,4);
  h2_jetDeltaR_higgsCandidateMass->SetMarkerStyle(21);
  h2_jetDeltaR_higgsCandidateMass->SetFillColor(kRed);
  h2_jetDeltaR_higgsCandidateMass->SetFillStyle(3002);
  h2_jetDeltaR_higgsCandidateMass->SetMarkerColor(kBlack);
  h2_jetDeltaR_higgsCandidateMass->DrawNormalized("COLZ");
  c21->Print("ZH_channel_v3/plots/c21.png");


  c24->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_jetDeltaR_jetPtAsymmetry->SetTitle("deltaR vs ptAsymmetry VJets herwig");
  h2_jetDeltaR_jetPtAsymmetry->GetYaxis()->SetTitle("ptAsymmetry");
  h2_jetDeltaR_jetPtAsymmetry->GetXaxis()->SetTitle("deltaR");
  h2_jetDeltaR_jetPtAsymmetry->GetYaxis()->SetLabelSize(0.03);
  h2_jetDeltaR_jetPtAsymmetry->GetYaxis()->SetRangeUser(60,160);
  h2_jetDeltaR_jetPtAsymmetry->GetXaxis()->SetLabelSize(0.03);
  h2_jetDeltaR_jetPtAsymmetry->GetXaxis()->SetRangeUser(0,4);
  h2_jetDeltaR_jetPtAsymmetry->SetMarkerStyle(21);
  h2_jetDeltaR_jetPtAsymmetry->SetFillColor(kCyan);
  h2_jetDeltaR_jetPtAsymmetry->SetFillStyle(3002);
  h2_jetDeltaR_jetPtAsymmetry->SetMarkerColor(kBlack);
  h2_jetDeltaR_jetPtAsymmetry->DrawNormalized("COLZ");
  c24->Print("ZH_channel_v3/plots/c24.png");

  c27->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_jetDeltaEta_jetDeltaR->SetTitle("deltaR vs ptasymmetry signal VJets herwig");
  h2_jetDeltaEta_jetDeltaR->GetYaxis()->SetTitle("#Delta R");
  h2_jetDeltaEta_jetDeltaR->GetXaxis()->SetTitle("#Delta #eta");
  h2_jetDeltaEta_jetDeltaR->GetYaxis()->SetLabelSize(0.03);
  h2_jetDeltaEta_jetDeltaR->GetYaxis()->SetRangeUser(60,160);
  h2_jetDeltaEta_jetDeltaR->GetXaxis()->SetLabelSize(0.03);
  h2_jetDeltaEta_jetDeltaR->GetXaxis()->SetRangeUser(0,4);
  h2_jetDeltaEta_jetDeltaR->SetMarkerStyle(21);
  h2_jetDeltaEta_jetDeltaR->SetFillColor(kCyan);
  h2_jetDeltaEta_jetDeltaR->SetFillStyle(3002);
  h2_jetDeltaEta_jetDeltaR->SetMarkerColor(kBlack);
  h2_jetDeltaEta_jetDeltaR->DrawNormalized("COLZ");
  c27->Print("ZH_channel_v3/plots/c27.png");

  c31->cd();
  //  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_deltaTheta_invmassJet->SetTitle("Pull angle vs invmass VJets herwig");
  h2_deltaTheta_invmassJet->GetXaxis()->SetTitle("#Delta #theta_{t}");
  h2_deltaTheta_invmassJet->GetYaxis()->SetTitle("M_{jj}");
  h2_deltaTheta_invmassJet->RebinY(10);
  h2_deltaTheta_invmassJet->RebinX(10);
  h2_deltaTheta_invmassJet->GetYaxis()->SetLabelSize(0.03);
  h2_deltaTheta_invmassJet->GetXaxis()->SetLabelSize(0.03);
  h2_deltaTheta_invmassJet->GetXaxis()->SetRangeUser(-4,4);
  h2_deltaTheta_invmassJet->SetMarkerStyle(21);
  h2_deltaTheta_invmassJet->SetFillColor(kCyan);
  h2_deltaTheta_invmassJet->SetFillStyle(3102);
  h2_deltaTheta_invmassJet->SetMarkerColor(kBlack);
  h2_deltaTheta_invmassJet->DrawNormalized("COLZ");
  c31->Print("ZH_channel_v3/plots/c31.png");

  c34->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_deltaTheta_JetDeltaR->SetTitle("Pull angle vs dR VJets herwig");
  h2_deltaTheta_JetDeltaR->RebinX(10);
  h2_deltaTheta_JetDeltaR->RebinY(10);
  h2_deltaTheta_JetDeltaR->GetYaxis()->SetTitle("#Delta R");
  h2_deltaTheta_JetDeltaR->GetXaxis()->SetTitle("#Delta #theta_{t}");
  h2_deltaTheta_JetDeltaR->GetYaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaR->GetXaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaR->GetXaxis()->SetRangeUser(-4,4);
  h2_deltaTheta_JetDeltaR->SetMarkerStyle(21);
  h2_deltaTheta_JetDeltaR->SetFillColor(kCyan);
  h2_deltaTheta_JetDeltaR->SetFillStyle(3002);
  h2_deltaTheta_JetDeltaR->SetMarkerColor(kBlack);
  h2_deltaTheta_JetDeltaR->DrawNormalized("COLZ");
  c34->Print("ZH_channel_v3/plots/c34.png");
 
  c37->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_deltaTheta_JetDeltaEta->SetTitle("Pull angle vs dEta VJet herwig");
  h2_deltaTheta_JetDeltaEta->RebinX(10);
  h2_deltaTheta_JetDeltaEta->RebinY(10);
  h2_deltaTheta_JetDeltaEta->GetXaxis()->SetTitle("#Delta #theta_{t}");
  h2_deltaTheta_JetDeltaEta->GetYaxis()->SetTitle("#Delta #eta");
  h2_deltaTheta_JetDeltaEta->GetYaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaEta->GetXaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaEta->GetXaxis()->SetRangeUser(-4,4);
  h2_deltaTheta_JetDeltaEta->SetMarkerStyle(21);
  h2_deltaTheta_JetDeltaEta->SetFillColor(kCyan);
  h2_deltaTheta_JetDeltaEta->SetFillStyle(3002);
  h2_deltaTheta_JetDeltaEta->SetMarkerColor(kBlack);
  h2_deltaTheta_JetDeltaEta->DrawNormalized("COLZ");
  c37->Print("ZH_channel_v3/plots/c37.png");

  c40->cd();
  //  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_deltaTheta_JetDeltaPhi->SetTitle("Pull angle vs dPhi VJets herwig"); 
  h2_deltaTheta_JetDeltaPhi->RebinY(10); 
  h2_deltaTheta_JetDeltaPhi->RebinX(10);
  h2_deltaTheta_JetDeltaPhi->GetXaxis()->SetTitle("#Delta #theta_{t}"); 
  h2_deltaTheta_JetDeltaPhi->GetYaxis()->SetTitle("#Delta #phi"); 
  h2_deltaTheta_JetDeltaPhi->GetYaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaPhi->GetXaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaPhi->GetXaxis()->SetRangeUser(-4,4);
  h2_deltaTheta_JetDeltaPhi->SetMarkerStyle(21);
  h2_deltaTheta_JetDeltaPhi->SetFillColor(kCyan);
  h2_deltaTheta_JetDeltaPhi->SetFillStyle(3002);
  h2_deltaTheta_JetDeltaPhi->SetMarkerColor(kBlack);
  h2_deltaTheta_JetDeltaPhi->DrawNormalized("COLZ");
  c40->Print("ZH_channel_v3/plots/c40.png");

  c49->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_JetDeltaEta_invmassJet->SetTitle("Jet #Delta #eta general VJets herwig");
  h2_JetDeltaEta_invmassJet->RebinX(4);
  h2_JetDeltaEta_invmassJet->RebinY(10);
  h2_JetDeltaEta_invmassJet->GetYaxis()->SetLabelSize(0.03);
  h2_JetDeltaEta_invmassJet->GetXaxis()->SetLabelSize(0.03);
  h2_JetDeltaEta_invmassJet->GetXaxis()->SetRangeUser(-0.1,3);
  h2_JetDeltaEta_invmassJet->SetMarkerStyle(21);
  h2_JetDeltaEta_invmassJet->SetFillColor(kCyan);
  h2_JetDeltaEta_invmassJet->SetFillStyle(3002);
  h2_JetDeltaEta_invmassJet->SetMarkerColor(kBlack);
  h2_JetDeltaEta_invmassJet->DrawNormalized("COLZ");
  c49->Print("ZH_channel_v3/plots/c49.png");

  c52->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_JetDeltaR_invmassJet->SetTitle("Jet #Delta R general VJets herwig");
  h2_JetDeltaR_invmassJet->RebinX(4);
  h2_JetDeltaR_invmassJet->RebinY(10);
  h2_JetDeltaR_invmassJet->GetYaxis()->SetLabelSize(0.03);
  h2_JetDeltaR_invmassJet->GetXaxis()->SetLabelSize(0.03);
  h2_JetDeltaR_invmassJet->GetXaxis()->SetRangeUser(0,5);
  h2_JetDeltaR_invmassJet->SetMarkerStyle(21);
  h2_JetDeltaR_invmassJet->SetFillColor(kCyan);
  h2_JetDeltaR_invmassJet->SetFillStyle(3002);
  h2_JetDeltaR_invmassJet->SetMarkerColor(kBlack);
  h2_JetDeltaR_invmassJet->DrawNormalized("COLZ");
  c52->Print("ZH_channel_v3/plots/c52.png");

  c58->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_jetPtAsymmetry_invmassJet->RebinX(8);
  h2_jetPtAsymmetry_invmassJet->RebinY(10);
  h2_jetPtAsymmetry_invmassJet->SetTitle("pt_asymmetry_invmass");
  h2_jetPtAsymmetry_invmassJet->GetYaxis()->SetTitle("inv_mass");
  h2_jetPtAsymmetry_invmassJet->GetXaxis()->SetTitle("jet pt asymmetry");
  h2_jetPtAsymmetry_invmassJet->GetYaxis()->SetLabelSize(0.03);
  h2_jetPtAsymmetry_invmassJet->GetXaxis()->SetLabelSize(0.03);
  h2_jetPtAsymmetry_invmassJet->SetMarkerStyle(21);
  h2_jetPtAsymmetry_invmassJet->SetFillColor(kCyan);
  h2_jetPtAsymmetry_invmassJet->SetFillStyle(3002);
  h2_jetPtAsymmetry_invmassJet->SetMarkerColor(kBlack);
  h2_jetPtAsymmetry_invmassJet->DrawNormalized("COLZ");
  c58->Print("ZH_channel_v3/plots/c58.png");


  //CAMBIO FILE : Background da MADGRAPH

  //  TFile::Open("./DQM_V0001_R000000001__POG__BTAG__IVF_BJET_TTbar.root");
  //  TFile::Open(IVF_file);

  std::string background = path+"/ZH_channel_background"+additional.c_str()+"/ZH_channel_background"+additional.c_str()+".root";
  TFile::Open(background.c_str());

  // Tagger : combinedSecondaryVertexBJetTags

  gDirectory->cd(subDir.c_str());

  c0->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_Zcandidate_mass->SetTitle("Z candidate mass V+Jets");
  h_Zcandidate_mass->GetYaxis()->SetLabelSize(0.03);
  h_Zcandidate_mass->GetXaxis()->SetLabelSize(0.03);
  h_Zcandidate_mass->SetMarkerStyle(20);
  h_Zcandidate_mass->SetFillColor(kYellow);
  h_Zcandidate_mass->SetFillStyle(3002);
  h_Zcandidate_mass->SetMarkerColor(kRed);
  h_Zcandidate_mass->DrawNormalized("same");
  TLegend* Legend = (TLegend*)gPad->BuildLegend( 0.15, 0.67, 0.48, 0.88);
  Legend->SetFillColor(kYellow);
  Legend->SetFillStyle(3002);

  c1->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_higgsCandidate_mass->Rebin(8);
  h_higgsCandidate_mass->SetTitle("higgs candidate mass VJets");
  h_higgsCandidate_mass->GetYaxis()->SetLabelSize(0.03);
  h_higgsCandidate_mass->GetXaxis()->SetLabelSize(0.03);
  h_higgsCandidate_mass->SetMarkerStyle(20);
  h_higgsCandidate_mass->SetFillColor(kYellow);
  h_higgsCandidate_mass->SetFillStyle(3002);
  h_higgsCandidate_mass->SetMarkerColor(kRed);
  h_higgsCandidate_mass->DrawNormalized("same");
  TLegend* Legend = (TLegend*)gPad->BuildLegend( 0.15, 0.67, 0.48, 0.88);
  Legend->SetFillColor(kYellow);
  Legend->SetFillStyle(3002);
  c1->Print("ZH_channel_v3/plots/c1.png");

  c2->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h_deltaTheta->SetTitle("Pull angle VJets");
  h_deltaTheta->Rebin(10);
  h_deltaTheta->GetYaxis()->SetTitle("#Delta #theta_{t}");
  h_deltaTheta->GetYaxis()->SetLabelSize(0.03);
  h_deltaTheta->GetXaxis()->SetLabelSize(0.03);
  h_deltaTheta->SetMarkerStyle(20);
  h_deltaTheta->SetFillColor(kYellow);
  h_deltaTheta->SetFillStyle(3002);
  h_deltaTheta->SetMarkerColor(kRed);
  h_deltaTheta->DrawNormalized("same");
//   TLegend* Legend = (TLegend*)gPad->BuildLegend( 0.15, 0.27, 0.48, 0.48);
  TLegend* Legend = (TLegend*)gPad->BuildLegend();
  Legend->SetFillColor(kYellow);
  Legend->SetFillStyle(3002);
  c2->Print("ZH_channel_v3/plots/c2.png");

  c3->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_HigherDeltaTheta->SetTitle("Pull angle leading jet VJets");
  h_HigherDeltaTheta->Rebin(10);
  h_HigherDeltaTheta->GetYaxis()->SetTitle("#Delta #theta_{t}");
  h_HigherDeltaTheta->GetYaxis()->SetLabelSize(0.03);
  h_HigherDeltaTheta->GetXaxis()->SetLabelSize(0.03);
  h_HigherDeltaTheta->SetMarkerStyle(20);
  h_HigherDeltaTheta->SetFillColor(kYellow);
  h_HigherDeltaTheta->SetFillStyle(3002);
  h_HigherDeltaTheta->SetMarkerColor(kRed);
  h_HigherDeltaTheta->DrawNormalized("same");
  TLegend* Legend = (TLegend*)gPad->BuildLegend();
  Legend->SetFillColor(kYellow);
  Legend->SetFillStyle(3002);
  c3->Print("ZH_channel_v3/plots/c3.png");

  c4->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_LowerDeltaTheta->SetTitle("Pull angle second leading jet VJets");
  h_LowerDeltaTheta->Rebin(10);
  h_LowerDeltaTheta->GetYaxis()->SetLabelSize(0.03);
  h_LowerDeltaTheta->GetXaxis()->SetLabelSize(0.03);
  h_LowerDeltaTheta->SetMarkerStyle(20);
  h_LowerDeltaTheta->SetFillColor(kYellow);
  h_LowerDeltaTheta->SetFillStyle(3002);
  h_LowerDeltaTheta->SetMarkerColor(kRed);
  h_LowerDeltaTheta->DrawNormalized("same");
  TLegend* Legend = (TLegend*)gPad->BuildLegend( 0.45, 0.27, 0.88, 0.48);
  Legend->SetFillColor(kYellow);
  Legend->SetFillStyle(3002);
  c4->Print("ZH_channel_v3/plots/c4.png");

  c5->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_jetDeltaEtaGeneral->SetTitle("jet #Delta #eta general V+Jets");
  h_jetDeltaEtaGeneral->Rebin(4);
  h_jetDeltaEtaGeneral->GetYaxis()->SetLabelSize(0.03);
  h_jetDeltaEtaGeneral->GetYaxis()->SetRangeUser(0,0.5);
  h_jetDeltaEtaGeneral->GetXaxis()->SetLabelSize(0.03);
  h_jetDeltaEtaGeneral->SetMarkerStyle(20);
  h_jetDeltaEtaGeneral->SetFillColor(kYellow);
  h_jetDeltaEtaGeneral->SetFillStyle(3002);
  h_jetDeltaEtaGeneral->SetMarkerColor(kRed);
  h_jetDeltaEtaGeneral->DrawNormalized("same");
//   TLegend* Legend = (TLegend*)gPad->BuildLegend( 0.15, 0.67, 0.48, 0.88);
  TLegend* Legend = (TLegend*)gPad->BuildLegend();
  Legend->SetFillColor(kYellow);
  Legend->SetFillStyle(3002);
  c5->Print("ZH_channel_v3/plots/c8.png");

  c6->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_jetDeltaR_general->SetTitle("jet #Delta R general V+Jets");
  h_jetDeltaR_general->Rebin(4);
  h_jetDeltaR_general->GetYaxis()->SetLabelSize(0.03);
  h_jetDeltaR_general->GetXaxis()->SetLabelSize(0.03);
  h_jetDeltaR_general->SetMarkerStyle(20);
  h_jetDeltaR_general->SetFillColor(kYellow);
  h_jetDeltaR_general->SetFillStyle(3002);
  h_jetDeltaR_general->SetMarkerColor(kRed);
  h_jetDeltaR_general->DrawNormalized("same");
  TLegend* Legend = (TLegend*)gPad->BuildLegend( 0.55, 0.67, 0.98, 0.88);
  Legend->SetFillColor(kYellow);
  Legend->SetFillStyle(3002);
  c6->Print("ZH_channel_v3/plots/c9.png");

  c7->cd();
  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_invmassJet_general->SetTitle("diJet mass V+Jets");
  h_invmassJet_general->Rebin(8);
  h_invmassJet_general->GetYaxis()->SetTitle("mass");
  h_invmassJet_general->GetYaxis()->SetLabelSize(0.03);
  h_invmassJet_general->GetXaxis()->SetLabelSize(0.03);
  h_invmassJet_general->SetMarkerStyle(20);
  h_invmassJet_general->SetFillColor(kYellow);
  h_invmassJet_general->SetFillStyle(3002);
  h_invmassJet_general->SetMarkerColor(kRed);
  h_invmassJet_general->DrawNormalized("same");
  TLegend* Legend = (TLegend*)gPad->BuildLegend();
  Legend->SetFillColor(kYellow);
  Legend->SetFillStyle(3002);
  c7->Print("ZH_channel_v3/plots/c11.png");

  c8->cd();
  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h_jetPtAsymmetryGeneral->SetTitle("Pt asymmetry V+Jets");
  h_jetPtAsymmetryGeneral->Rebin(4);
  h_jetPtAsymmetryGeneral->GetYaxis()->SetLabelSize(0.03);
  h_jetPtAsymmetryGeneral->GetXaxis()->SetLabelSize(0.03);
  h_jetPtAsymmetryGeneral->SetMarkerStyle(20);
  h_jetPtAsymmetryGeneral->SetFillColor(kYellow);
  h_jetPtAsymmetryGeneral->SetFillStyle(3002);
  h_jetPtAsymmetryGeneral->SetMarkerColor(kRed);
  h_jetPtAsymmetryGeneral->DrawNormalized("same");
  TLegend* Legend = (TLegend*)gPad->BuildLegend( 0.55, 0.27, 0.88, 0.48);
  Legend->SetFillColor(kYellow);
  Legend->SetFillStyle(3002);
  c8->Print("ZH_channel_v3/plots/c12.png");

  c22->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_jetDeltaR_higgsCandidateMass->SetTitle("dR vs Mjj VJets");
  h2_jetDeltaR_higgsCandidateMass->GetYaxis()->SetTitle("M_{jj}");
  h2_jetDeltaR_higgsCandidateMass->GetYaxis()->SetTitle("#Delta R");
  h2_jetDeltaR_higgsCandidateMass->RebinX(2);
  h2_jetDeltaR_higgsCandidateMass->RebinY(16);
  h2_jetDeltaR_higgsCandidateMass->GetYaxis()->SetLabelSize(0.03);
  h2_jetDeltaR_higgsCandidateMass->GetYaxis()->SetRangeUser(60,160);
  h2_jetDeltaR_higgsCandidateMass->GetXaxis()->SetLabelSize(0.03);
  h2_jetDeltaR_higgsCandidateMass->GetXaxis()->SetRangeUser(0,4);
  h2_jetDeltaR_higgsCandidateMass->SetMarkerStyle(20);
  h2_jetDeltaR_higgsCandidateMass->SetFillColor(kYellow);
  h2_jetDeltaR_higgsCandidateMass->SetFillStyle(3002);
  h2_jetDeltaR_higgsCandidateMass->SetMarkerColor(kRed);
  h2_jetDeltaR_higgsCandidateMass->DrawNormalized("COLZ");
  c22->Print("ZH_channel_v3/plots/c22.png");

  c25->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_jetDeltaR_jetPtAsymmetry->SetTitle("deltaR vs ptAsymmetry VJets");
  h2_jetDeltaR_jetPtAsymmetry->GetYaxis()->SetTitle("p_{t} Asymmetry");
  h2_jetDeltaR_jetPtAsymmetry->GetXaxis()->SetTitle("#Delta R");
  h2_jetDeltaR_jetPtAsymmetry->GetYaxis()->SetLabelSize(0.03);
  h2_jetDeltaR_jetPtAsymmetry->GetYaxis()->SetRangeUser(60,160);
  h2_jetDeltaR_jetPtAsymmetry->GetXaxis()->SetLabelSize(0.03);
  h2_jetDeltaR_jetPtAsymmetry->GetXaxis()->SetRangeUser(0,4);
  h2_jetDeltaR_jetPtAsymmetry->SetMarkerStyle(21);
  h2_jetDeltaR_jetPtAsymmetry->SetFillColor(kCyan);
  h2_jetDeltaR_jetPtAsymmetry->SetFillStyle(3002);
  h2_jetDeltaR_jetPtAsymmetry->SetMarkerColor(kBlack);
  h2_jetDeltaR_jetPtAsymmetry->DrawNormalized("COLZ");
  c25->Print("ZH_channel_v3/plots/c25.png");

  c28->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_jetDeltaEta_jetDeltaR->SetTitle("dR vs dEta VJets");
  h2_jetDeltaEta_jetDeltaR->GetYaxis()->SetTitle("#Delta R");
  h2_jetDeltaEta_jetDeltaR->GetXaxis()->SetTitle("#Delta #eta");
  h2_jetDeltaEta_jetDeltaR->GetYaxis()->SetLabelSize(0.03);
  h2_jetDeltaEta_jetDeltaR->GetYaxis()->SetRangeUser(60,160);
  h2_jetDeltaEta_jetDeltaR->GetXaxis()->SetLabelSize(0.03);
  h2_jetDeltaEta_jetDeltaR->GetXaxis()->SetRangeUser(0,4);
  h2_jetDeltaEta_jetDeltaR->SetMarkerStyle(21);
  h2_jetDeltaEta_jetDeltaR->SetFillColor(kCyan);
  h2_jetDeltaEta_jetDeltaR->SetFillStyle(3002);
  h2_jetDeltaEta_jetDeltaR->SetMarkerColor(kBlack);
  h2_jetDeltaEta_jetDeltaR->DrawNormalized("COLZ");
  c28->Print("ZH_channel_v3/plots/c28.png");

  c32->cd();
  //  gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_deltaTheta_invmassJet->SetTitle("Pull angle vs Mjj VJets");
  h2_deltaTheta_invmassJet->GetXaxis()->SetTitle("#Delta #theta_{t}");
  h2_deltaTheta_invmassJet->GetYaxis()->SetTitle("M_{jj}");
  h2_deltaTheta_invmassJet->RebinY(10);
  h2_deltaTheta_invmassJet->RebinX(10);
  h2_deltaTheta_invmassJet->GetYaxis()->SetLabelSize(0.03);
  h2_deltaTheta_invmassJet->GetXaxis()->SetLabelSize(0.03);
  h2_deltaTheta_invmassJet->GetXaxis()->SetRangeUser(-4,4);
  h2_deltaTheta_invmassJet->SetMarkerStyle(21);
  h2_deltaTheta_invmassJet->SetFillColor(kCyan);
  h2_deltaTheta_invmassJet->SetFillStyle(3202);
  h2_deltaTheta_invmassJet->SetMarkerColor(kBlack);
  h2_deltaTheta_invmassJet->DrawNormalized("COLZ");
  c32->Print("ZH_channel_v3/plots/c32.png");


  c35->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_deltaTheta_JetDeltaR->SetTitle("Pull angle vs dR VJets");
  h2_deltaTheta_JetDeltaR->RebinX(10);
  h2_deltaTheta_JetDeltaR->RebinY(10);
  h2_deltaTheta_JetDeltaR->GetYaxis()->SetTitle("M_{jj}");
  h2_deltaTheta_JetDeltaR->GetXaxis()->SetTitle("#Delta #theta_{t}");
  h2_deltaTheta_JetDeltaR->GetYaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaR->GetXaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaR->GetXaxis()->SetRangeUser(-1,2);
  h2_deltaTheta_JetDeltaR->SetMarkerStyle(21);
  h2_deltaTheta_JetDeltaR->SetFillColor(kCyan);
  h2_deltaTheta_JetDeltaR->SetFillStyle(3002);
  h2_deltaTheta_JetDeltaR->SetMarkerColor(kBlack);
  h2_deltaTheta_JetDeltaR->DrawNormalized("COLZ");
  c35->Print("ZH_channel_v3/plots/c35.png");

 
  c38->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_deltaTheta_JetDeltaEta->SetTitle("Pull angle vs dEta VJets");
  h2_deltaTheta_JetDeltaEta->RebinX(10);
  h2_deltaTheta_JetDeltaEta->RebinY(10);
  h2_deltaTheta_JetDeltaEta->GetXaxis()->SetTitle("#Delta #theta_{t}");
  h2_deltaTheta_JetDeltaEta->GetYaxis()->SetTitle("#Delta #eta");
  h2_deltaTheta_JetDeltaEta->GetYaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaEta->GetXaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaEta->GetXaxis()->SetRangeUser(-4,4);
  h2_deltaTheta_JetDeltaEta->SetMarkerStyle(21);
  h2_deltaTheta_JetDeltaEta->SetFillColor(kCyan);
  h2_deltaTheta_JetDeltaEta->SetFillStyle(3002);
  h2_deltaTheta_JetDeltaEta->SetMarkerColor(kBlack);
  h2_deltaTheta_JetDeltaEta->DrawNormalized("COLZ");
  c38->Print("ZH_channel_v3/plots/c38.png");

  c41->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_deltaTheta_JetDeltaPhi->SetTitle("Pull angle vs dPhi VJets");
  h2_deltaTheta_JetDeltaPhi->RebinX(10);
  h2_deltaTheta_JetDeltaPhi->RebinY(10);
  h2_deltaTheta_JetDeltaPhi->GetXaxis()->SetTitle("#Delta #theta_{t}");
  h2_deltaTheta_JetDeltaPhi->GetYaxis()->SetTitle("#Delta #phi");
  h2_deltaTheta_JetDeltaPhi->GetYaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaPhi->GetXaxis()->SetLabelSize(0.03);
  h2_deltaTheta_JetDeltaPhi->GetXaxis()->SetRangeUser(-4,4);
  h2_deltaTheta_JetDeltaPhi->SetMarkerStyle(21);
  h2_deltaTheta_JetDeltaPhi->SetFillColor(kCyan);
  h2_deltaTheta_JetDeltaPhi->SetFillStyle(3002);
  h2_deltaTheta_JetDeltaPhi->SetMarkerColor(kBlack);
  h2_deltaTheta_JetDeltaPhi->DrawNormalized("COLZ");
  c41->Print("ZH_channel_v3/plots/c41.png");

  c50->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_JetDeltaEta_invmassJet->SetTitle("Jet #Delta #eta general VJets");
  h2_JetDeltaEta_invmassJet->RebinX(4);
  h2_JetDeltaEta_invmassJet->RebinY(10);
  h2_JetDeltaEta_invmassJet->GetYaxis()->SetLabelSize(0.03);
  h2_JetDeltaEta_invmassJet->GetXaxis()->SetLabelSize(0.03);
  h2_JetDeltaEta_invmassJet->GetXaxis()->SetRangeUser(-0.1,3);
  h2_JetDeltaEta_invmassJet->SetMarkerStyle(21);
  h2_JetDeltaEta_invmassJet->SetFillColor(kCyan);
  h2_JetDeltaEta_invmassJet->SetFillStyle(3002);
  h2_JetDeltaEta_invmassJet->SetMarkerColor(kBlack);
  h2_JetDeltaEta_invmassJet->DrawNormalized("COLZ");
  c50->Print("ZH_channel_v3/plots/c50.png");

  c53->cd();
//   gPad->SetLogy();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_JetDeltaR_invmassJet->SetTitle("Jet #Delta R general VJets");
  h2_JetDeltaR_invmassJet->RebinX(4);
  h2_JetDeltaR_invmassJet->RebinY(10);
  h2_JetDeltaR_invmassJet->GetYaxis()->SetLabelSize(0.03);
  h2_JetDeltaR_invmassJet->GetXaxis()->SetLabelSize(0.03);
  h2_JetDeltaR_invmassJet->GetXaxis()->SetRangeUser(0,5);
  h2_JetDeltaR_invmassJet->SetMarkerStyle(21);
  h2_JetDeltaR_invmassJet->SetFillColor(kCyan);
  h2_JetDeltaR_invmassJet->SetFillStyle(3002);
  h2_JetDeltaR_invmassJet->SetMarkerColor(kBlack);
  h2_JetDeltaR_invmassJet->DrawNormalized("COLZ");
  c53->Print("ZH_channel_v3/plots/c53.png");

  c59->cd();
  gPad->SetGridy();
  gPad->SetGridx();
  h2_jetPtAsymmetry_invmassJet->RebinX(8);
  h2_jetPtAsymmetry_invmassJet->RebinY(10);
  h2_jetPtAsymmetry_invmassJet->SetTitle("pt_asymmetry_invmass VJets");
  h2_jetPtAsymmetry_invmassJet->GetYaxis()->SetTitle("inv_mass");
  h2_jetPtAsymmetry_invmassJet->GetXaxis()->SetTitle("jet pt asymmetry");
  h2_jetPtAsymmetry_invmassJet->GetYaxis()->SetLabelSize(0.03);
  h2_jetPtAsymmetry_invmassJet->GetXaxis()->SetLabelSize(0.03);
  h2_jetPtAsymmetry_invmassJet->SetMarkerStyle(21);
  h2_jetPtAsymmetry_invmassJet->SetFillColor(kCyan);
  h2_jetPtAsymmetry_invmassJet->SetFillStyle(3002);
  h2_jetPtAsymmetry_invmassJet->SetMarkerColor(kBlack);
  h2_jetPtAsymmetry_invmassJet->DrawNormalized("COLZ");
  c59->Print("ZH_channel_v3/plots/c59.png");

  return 0;

}

//  LocalWords:  SetGridy
